### ISSUE TITLE
No data in my data frames!

### ISSUE THREAD

**Issue by daveaitel** [G-Research/spark-dgraph-connector#128]
Hi! I'm not getting any data returned from my dataframes using the spark-dgraph-connector on my v21.03.1 (from standalone docker image) dgraph instance (spark is version 3.1.2) . I have a ton of data in my dgraph instance (which I can browse with Ratel perfectly fine).

pyspark --packages uk.co.gresearch.spark:spark-dgraph-connector_2.12:0.6.0-3.1,graphframes:graphframes:0.8.1-spark3.0-s_2.12

from gresearch.spark.dgraph.connector import *

#If I use a different port I get an error - so it IS connecting
triples: DataFrame = spark.read.dgraph.triples("localhost:9080")
edges: DataFrame = spark.read.dgraph.edges("localhost:9080")
nodes: DataFrame = spark.read.dgraph.nodes("localhost:9080")

>>> triples.show()
+-------+---------+---------+------------+----------+------------+---------------+-------------+---------+--------------+----------+
|subject|predicate|objectUid|objectString|objectLong|objectDouble|objectTimestamp|objectBoolean|objectGeo|objectPassword|objectType|
+-------+---------+---------+------------+----------+------------+---------------+-------------+---------+--------------+----------+
+-------+---------+---------+------------+----------+------------+---------------+-------------+---------+--------------+----------+

>>> edges.show()
+-------+---------+---------+
|subject|predicate|objectUid|
+-------+---------+---------+
+-------+---------+---------+

>>> nodes.show()
+-------+---------+------------+----------+------------+---------------+-------------+---------+--------------+----------+
|subject|predicate|objectString|objectLong|objectDouble|objectTimestamp|objectBoolean|objectGeo|objectPassword|objectType|
+-------+---------+------------+----------+------------+---------------+-------------+---------+--------------+----------+
+-------+---------+------------+----------+------------+---------------+-------------+---------+--------------+----------+

Any help would be appreciated! Thanks so much!

From https://discuss.dgraph.io/t/spark-dgraph-connector-returning-no-data/15687.

**Comment by daveaitel** [comment]
Also, in Scala, I get this:

scala> val vertices: DataFrame = spark.read.dgraph.vertices(target)
vertices: org.apache.spark.sql.DataFrame = [id: bigint, absfile: string ... 21 more fields]

scala> import uk.co.gresearch.spark.dgraph.graphframes._
import uk.co.gresearch.spark.dgraph.graphframes._

scala> val graph: GraphFrame = spark.read.dgraph.graphframes("localhost:9080")
<console>:30: error: not found: type GraphFrame
       val graph: GraphFrame = spark.read.dgraph.graphframes("localhost:9080")
                  ^
<console>:30: error: Symbol 'term org.graphframes' is missing from the classpath.
This symbol is required by 'method uk.co.gresearch.spark.dgraph.graphframes.GraphFramesReader.graphframes'.
Make sure that term graphframes is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'GraphFramesReader.class' was compiled against an incompatible version of org.
       val graph: GraphFrame = spark.read.dgraph.graphframes("localhost:9080")
                                     ^

scala> import uk.co.gresearch.spark.dgraph.graphx._
import uk.co.gresearch.spark.dgraph.graphx._

scala> val graph = spark.read.dgraph.graphx("localhost:9080")
<console>:33: error: type mismatch;
 found   : org.apache.spark.sql.DataFrameReader
 required: ?{def dgraph: ?}
Note that implicit conversions are not applicable because they are ambiguous:
 both method GraphFrameDataFrameReader in package graphframes of type (reader: org.apache.spark.sql.DataFrameReader)uk.co.gresearch.spark.dgraph.graphframes.package.GraphFrameDataFrameReader
 and method GraphxDataFrameReader in package graphx of type (reader: org.apache.spark.sql.DataFrameReader)uk.co.gresearch.spark.dgraph.graphx.package.GraphxDataFrameReader
 are possible conversion functions from org.apache.spark.sql.DataFrameReader to ?{def dgraph: ?}
       val graph = spark.read.dgraph.graphx("localhost:9080")
                         ^

**Comment by EnricoMi** [comment]
How do you load data into your Dgraph instance? Did you use the bulk loader or live loader?

**Comment by daveaitel** [comment]
I used a live loader - a Python script that put a lot of data into the DB with mutations one at a time. This data does not (currently) have dgraph.type set. But it is large. 
![image](https://user-images.githubusercontent.com/20305506/135458094-e1206d25-f0c3-45d8-b045-d1c47b27dd5a.png)
![image](https://user-images.githubusercontent.com/20305506/135458254-0bf2aa6c-0e67-4ae0-9535-86f3f5ebbbe7.png)

**Comment by daveaitel** [comment]
FWIW, the connector IS definitely getting my schema. 

scala> graph.vertices.show(false)
+---+-------+------------+-------------+------------+----------------+--------------+------------+-------------+-----------+---------------+--------------+-----------------------+---------------------+------------------+-----------+-----------+-----------+--------+--------+----------+--------+-----------+
|id |absfile|author__date|author__email|author__name|author__timezone|comitter__date|commit__hash|commit__lines|commit__msg|committer__date|dgraph_drop_op|dgraph_graphql_p__query|dgraph_graphql_schema|dgraph_graphql_xid|dgraph_type|email__hash|email__text|filename|listname|node__type|reponame|subjectline|
+---+-------+------------+-------------+------------+----------------+--------------+------------+-------------+-----------+---------------+--------------+-----------------------+---------------------+------------------+-----------+-----------+-----------+--------+--------+----------+--------+-----------+
+---+-------+------------+-------------+------------+----------------+--------------+------------+-------------+-----------+---------------+--------------+-----------------------+---------------------+------------------+-----------+-----------+-----------+--------+--------+----------+--------+-----------+

**Comment by EnricoMi** [comment]
Can you run your Scala code with Log4J log level `TRACE` (set `log4j.logger.uk.co.gresearch.spark.dgraph=TRACE`) and check the logs for something like

    21/09/30 14:58:46 TRACE DgraphExecutor: querying dgraph cluster at [localhost:9080] with:
    {
      pred as var(func: has(<dgraph.graphql.xid>)) @filter(eq(<dgraph.graphql.xid>, "dgraph.graphql.schema"))
    
      result (func: uid(pred)) {
        uid
      }
    }

**Comment by EnricoMi** [comment]
Can you also check http://localhost:8080/state for me? What is the value for `maxUID`?

**Comment by daveaitel** [comment]
![image](https://user-images.githubusercontent.com/20305506/135462325-2873b673-fdeb-40b6-b963-52eff9b4eb96.png)


scala> import uk.co.gresearch.spark.dgraph.graphframes._
import uk.co.gresearch.spark.dgraph.graphframes._

scala> import org.apache.log4j.{Level, Logger}
import org.apache.log4j.{Level, Logger}

scala> Logger.getLogger("uk.co.gresearch.spark.dgraph").setLevel(Level.TRACE)

scala> val target = "localhost:9080"
target: String = localhost:9080

scala> val graph: GraphFrame = spark.read.dgraph.graphframes(target)
21/09/30 13:15:48 INFO DefaultSource: retrieved cluster state from localhost:9080 with 8243 bytes in 0.023s
21/09/30 13:15:48 TRACE DefaultSource: retrieved cluster state: {"counter":"70144065","groups":{"1":{"members":{"1":{"id":"1","groupId":1,"addr":"localhost:7080","leader":true,"amDead":false,"lastUpdate":"1632762605","learner":false,"clusterInfoOnly":false,"forceGroupId":false}},"tablets":{"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000absfile":{"groupId":1,"predicate":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000absfile","force":false,"onDiskBytes":"16265129","remove":false,"readOnly":false,"moveTs":"0","uncompressedBytes":"31565032"},"\u0000\u0000\u[…]sedBytes":"446877175"}},"snapshotTs":"235472682","checksum":"10542382788423639251","checkpointTs":"0"}},"zeros":{"1":{"id":"1","groupId":0,"addr":"localhost:5080","leader":true,"amDead":false,"lastUpdate":"0","learner":false,"clusterInfoOnly":false,"forceGroupId":false}},"maxUID":"6170000","maxTxnTs":"235520000","maxNsID":"0","maxRaftId":"1","removed":[],"cid":"4f34d701-b0a9-4deb-9779-04a60b33f8e4","license":{"user":"","maxNodes":"18446744073709551615","expiryTs":"1626299734","enabled":false}}
21/09/30 13:15:48 TRACE PredicatePartitioner: replaced filters: Set()
21/09/30 13:15:48 TRACE PredicatePartitioner: simplified filters: Set()
21/09/30 13:15:49 INFO DefaultSource: retrieved cluster state from localhost:9080 with 8243 bytes in 0.002s
21/09/30 13:15:49 TRACE DefaultSource: retrieved cluster state: {"counter":"70144065","groups":{"1":{"members":{"1":{"id":"1","groupId":1,"addr":"localhost:7080","leader":true,"amDead":false,"lastUpdate":"1632762605","learner":false,"clusterInfoOnly":false,"forceGroupId":false}},"tablets":{"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000absfile":{"groupId":1,"predicate":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000absfile","force":false,"onDiskBytes":"16265129","remove":false,"readOnly":false,"moveTs":"0","uncompressedBytes":"31565032"},"\u0000\u0000\u[…]sedBytes":"446877175"}},"snapshotTs":"235472682","checksum":"10542382788423639251","checkpointTs":"0"}},"zeros":{"1":{"id":"1","groupId":0,"addr":"localhost:5080","leader":true,"amDead":false,"lastUpdate":"0","learner":false,"clusterInfoOnly":false,"forceGroupId":false}},"maxUID":"6170000","maxTxnTs":"235520000","maxNsID":"0","maxRaftId":"1","removed":[],"cid":"4f34d701-b0a9-4deb-9779-04a60b33f8e4","license":{"user":"","maxNodes":"18446744073709551615","expiryTs":"1626299734","enabled":false}}
21/09/30 13:15:49 TRACE PredicatePartitioner: replaced filters: Set()
21/09/30 13:15:49 TRACE PredicatePartitioner: simplified filters: Set()
graph: org.graphframes.GraphFrame = GraphFrame(v:[id: bigint, absfile: string ... 21 more fields], e:[src: bigint, dst: bigint ... 1 more field])
scala> val vert = graph.vertices
vert: org.apache.spark.sql.DataFrame = [id: bigint, absfile: string ... 21 more fields]

scala> vert.show(false)
21/09/30 13:17:39 DEBUG TripleScanBuilder: required columns: subject, absfile, author_date, author_email, author_name, author_timezone, comitter_date, commit_hash, commit_lines, commit_msg, committer_date, dgraph.drop.op, dgraph.graphql.p_query, dgraph.graphql.schema, dgraph.graphql.xid, dgraph.type, email_hash, email_text, filename, listname, node_type, reponame, subjectline
21/09/30 13:17:39 TRACE PredicatePartitioner: replaced filters: Set()
21/09/30 13:17:39 TRACE PredicatePartitioner: simplified filters: Set()
+---+-------+------------+-------------+------------+----------------+--------------+------------+-------------+-----------+---------------+--------------+-----------------------+---------------------+------------------+-----------+-----------+-----------+--------+--------+----------+--------+-----------+
|id |absfile|author__date|author__email|author__name|author__timezone|comitter__date|commit__hash|commit__lines|commit__msg|committer__date|dgraph_drop_op|dgraph_graphql_p__query|dgraph_graphql_schema|dgraph_graphql_xid|dgraph_type|email__hash|email__text|filename|listname|node__type|reponame|subjectline|
+---+-------+------------+-------------+------------+----------------+--------------+------------+-------------+-----------+---------------+--------------+-----------------------+---------------------+------------------+-----------+-----------+-----------+--------+--------+----------+--------+-----------+
+---+-------+------------+-------------+------------+----------------+--------------+------------+-------------+-----------+---------------+--------------+-----------------------+---------------------+------------------+-----------+-----------+-----------+--------+--------+----------+--------+-----------+

**Comment by EnricoMi** [comment]
I might have found the issue. There is a fix in master that hasn't been released yet. Can you try to build master (git clone; mvn package) and use that locally build version of the connector library?

**Comment by daveaitel** [comment]
I'm happy to try! (thanks for your help btw!!!). I'm admittedly not a huge Java programmer but I will do so now.

**Comment by daveaitel** [comment]
I'm running into this weird error trying to grab the graphframes dependency. My inexperience with Java is showing, I fear. :(

$ mvn package

[INFO] --------------------------------[ jar ]---------------------------------
Downloading from bintray: https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.pom
Downloading from bintray: https://dl.bintray.com/spark-packages/maven/io/grpc/grpc-core/maven-metadata.xml
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to bintray (https://dl.bintray.com/spark-packages/maven/): Authorization failed for https://dl.bintray.com/spark-packages/maven/io/grpc/grpc-core/maven-metadata.xml 403 Forbidden
Downloading from bintray: https://dl.bintray.com/spark-packages/maven/io/grpc/grpc-api/maven-metadata.xml
[WARNING] Could not transfer metadata io.grpc:grpc-api/maven-metadata.xml from/to bintray (https://dl.bintray.com/spark-packages/maven/): Authorization failed for https://dl.bintray.com/spark-packages/maven/io/grpc/grpc-api/maven-metadata.xml 403 Forbidden
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.036 s
[INFO] Finished at: 2021-09-30T13:35:07Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spark-dgraph-connector_2.12: Could not resolve dependencies for project uk.co.gresearch.spark:spark-dgraph-connector_2.12:jar:0.7.0-3.1-SNAPSHOT: Failed to collect dependencies at graphframes:graphframes:jar:0.8.1-spark3.0-s_2.12: Failed to read artifact descriptor for graphframes:graphframes:jar:0.8.1-spark3.0-s_2.12: Could not transfer artifact graphframes:graphframes:pom:0.8.1-spark3.0-s_2.12 from/to bintray (https://dl.bintray.com/spark-packages/maven/): Authorization failed for https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.8.1-spark3.0-s_2.12/graphframes-0.8.1-spark3.0-s_2.12.pom 403 Forbidden -> [Help 1]
[ERROR]

**Comment by EnricoMi** [comment]
I have just fixed this in master (well, branch spark-3.1), just `git pull` and try again.

**Comment by daveaitel** [comment]
The compile succeeds for me now up to when this test fails (which I'm sure is my fault somehow).

- should noop group partitioner with too large uidsPerPartition
- should noop alpha partitioner with too large uidsPerPartition
- should noop predicates partitioner with too large uidsPerPartition
- should fail on null partitioner
- should fail with integer overflow partition size
- should fail on decorating uid partitioner
- should support what decorated partitioner supports
- should forward filters to decorated partitioner
- should forward projection to decorated partitioner
- should provide lang directives
21/09/30 14:02:58 INFO DgraphTestCluster$$anon$1: retrieved cluster state from localhost:9080 with 8243 bytes in 0.02s
TestGraphX:
21/09/30 14:02:58 INFO DgraphTestCluster$: Docker: Docker version 20.10.8, build 3967b7d28e
*** RUN ABORTED ***
  java.io.FileNotFoundException: ./dgraph-instance.inserted.json (No such file or directory)
  at java.base/java.io.FileInputStream.open0(Native Method)
  at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
  at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
  at scala.io.Source$.fromFile(Source.scala:94)
  at scala.io.Source$.fromFile(Source.scala:79)
  at scala.io.Source$.fromFile(Source.scala:57)
  at uk.co.gresearch.spark.dgraph.DgraphCluster.start(DgraphTestCluster.scala:93)
  at uk.co.gresearch.spark.dgraph.DgraphTestCluster.beforeAll(DgraphTestCluster.scala:45)
  at uk.co.gresearch.spark.dgraph.DgraphTestCluster.beforeAll$(DgraphTestCluster.scala:45)
  at uk.co.gresearch.spark.dgraph.graphx.TestGraphX.beforeAll(TestGraphX.scala:28)

**Comment by daveaitel** [comment]
~/CODE/spark-dgraph-connector$ find . -name "dgraph-instance*"
./dgraph-instance.schema.sh
./dgraph-instance.insert.sh
./dgraph-instance.start.sh
./dgraph-instance.background.sh
./dgraph-instance.drop-all.sh

I have insert but not "inserted".

**Comment by EnricoMi** [comment]
right, you would have to follow README.md instructions on testing, but for now simply skip tests:

    mvn package -DskipTests=true

**Comment by daveaitel** [comment]
I have compiled it, and used -jars to place it into my spark shell session! Thanks for your help!

The DGraph server still appears to be up and running but: 

scala> import org.graphframes.GraphFrame
import org.graphframes.GraphFrame

scala> import uk.co.gresearch.spark.dgraph.graphframes._
import uk.co.gresearch.spark.dgraph.graphframes._

scala> import org.apache.log4j.{Level, Logger}
import org.apache.log4j.{Level, Logger}

scala> Logger.getLogger("uk.co.gresearch.spark.dgraph").setLevel(Level.TRACE)


scala> val target = "localhost:9080"
target: String = localhost:9080

scala> val graph: GraphFrame = spark.read.dgraph.graphframes(target)
21/09/30 14:31:57 ERROR DefaultSource: retrieving state from http://localhost:8080/state failed: requests/package$
java.lang.RuntimeException: Could not retrieve cluster state from Dgraph alphas (localhost:9080)
  at uk.co.gresearch.spark.dgraph.connector.ClusterStateProvider.$anonfun$getClusterState$5(ClusterStateProvider.scala:32)
  at scala.Option.getOrElse(Option.scala:189)
  at uk.co.gresearch.spark.dgraph.connector.ClusterStateProvider.getClusterState(ClusterStateProvider.scala:32)
  at uk.co.gresearch.spark.dgraph.connector.ClusterStateProvider.getClusterState$(ClusterStateProvider.scala:25)
  at uk.co.gresearch.spark.dgraph.connector.sources.NodeSource.getClusterState(NodeSource.scala:33)
  at uk.co.gresearch.spark.dgraph.connector.sources.NodeSource.getTable(NodeSource.scala:89)
  at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Utils$.getTableFromProvider(DataSourceV2Utils.scala:83)
  at org.apache.spark.sql.DataFrameReader.$anonfun$load$1(DataFrameReader.scala:295)
  at scala.Option.map(Option.scala:230)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:265)
  at uk.co.gresearch.spark.dgraph.connector.DgraphReader.nodes(DgraphReader.scala:59)
  at uk.co.gresearch.spark.dgraph.graphframes.package$.loadVertices(package.scala:40)
  at uk.co.gresearch.spark.dgraph.graphframes.package$.loadGraph(package.scala:30)
  at uk.co.gresearch.spark.dgraph.graphframes.GraphFramesReader.graphframes(GraphFramesReader.scala:25)
  ... 49 elided

**Comment by daveaitel** [comment]
I'm currently making sure this isn't user error - restarting the server/etc.

**Comment by daveaitel** [comment]
I can't see anything wrong with the setup at this time, but also: I don't see traces as it tries to connect, which surprises me.

**Comment by daveaitel** [comment]
I see GRPC happening when I set the default to trace (which then shows me Netty stuff):
1/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x8cf52415, L:/127.0.0.1:50340 - R:localhost/127.0.0.1:9080] INBOUND PING: ack=true bytes=1234
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x8cf52415, L:/127.0.0.1:50340 - R:localhost/127.0.0.1:9080] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=1000, MAX_FRAME_SIZE=16384}
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND SETTINGS: ack=true
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND SETTINGS: ack=true
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:9080, :path: /api.Dgraph/Query, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.34.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=39 bytes=0000000022221e736368656d61207b207072656469636174652074797065206c616e67207d3001
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=39
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND PING: ack=false bytes=145258749040133895
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND PING: ack=true bytes=145258749040133895
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, dgraph-toucheduids: 0] padding=0 endStream=false
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND DATA: streamId=3 padding=0 endStream=false length=1437 bytes=00000005980aef0a7b22736368656d61223a5b7b22707265646963617465223a2261627366696c65222c2274797065223a22737472696e67227d2c7b22707265...
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND PING: ack=false bytes=1234
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0, grpc-message: ] padding=0 endStream=true
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] INBOUND PING: ack=true bytes=1234
21/09/30 15:49:12 DEBUG NettyClientHandler: [id: 0x775189ee, L:/127.0.0.1:50344 - R:localhost/127.0.0.1:9080] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
21/09/30 15:49:12 ERROR DefaultSource: retrieving state from http://localhost:8080/state failed: requests/package$
java.lang.RuntimeException: Could not retrieve cluster state from Dgraph alphas (localhost:9080)

**Comment by EnricoMi** [comment]
Can you access http://localhost:8080/state via your local Web browser?

**Comment by daveaitel** [comment]
Yes, is there a particular field I appear to be missing (see below)? Also, I'm unsure why the TRACE is not working - probably something I did wrong? 

![image](https://user-images.githubusercontent.com/20305506/135522305-e268adef-333f-4c6f-a2d2-f73a712ab4ed.png)
![image](https://user-images.githubusercontent.com/20305506/135522343-7c0f8e5e-ea58-4c19-88ae-9d5f28c8e07e.png)

**Comment by daveaitel** [comment]
I think we know for sure the GRPC is connecting because we see that traffic happening right?

**Comment by EnricoMi** [comment]
Yes, gRPC is working for sure but we also need the http://localhost:8080/state to work. Let me cut a new release so that the v21.03 fix is out and we try from there.

**Comment by EnricoMi** [comment]
I have released `v0.7.0-spark3.1` and `v0.7.0-spark3.0`, go for it.

**Comment by daveaitel** [comment]
Yes! It works! Thanks so much! (Now I have to work through the memory and partitioning stuff, but queries are doing great!) I wish I knew why the one I built didn't work, but ... moving on! :)

Awesome!

**Comment by EnricoMi** [comment]
Excellent. It puzzles me how the built jar could fail this way. Anyway, the release works and fixes this issue. Closing this then.

If you have questions around how to best partition your data, please raise another issue with specific information on the schema and cardinality and I might help. Try to set `dgraph.partitioner.predicate.predicatesPerPartition` to `1` and compare the performance to the default. Please get back with some performance measures, as in how long does the entire graph need to be read into Spark, and how large is it.
